image: python:3

stages:
 - build

.pio_run: &pio_run
  stage: build
  script:
    - "pip install -U platformio"
    - "platformio run $PLATFORMIO_CI_EXTRA_ARGS"
  artifacts:
    name: "$CI_JOB_NAME"
    expire_in: 4 weeks
    paths:
      - .pio/build/*/firmware.hex
      - .pio/build/*/firmware.map

ATmega32:
  <<: *pio_run
  variables:
    PLATFORMIO_CI_EXTRA_ARGS: '-e ATmega32'

ATmega328P:
  <<: *pio_run
  variables:
    PLATFORMIO_CI_EXTRA_ARGS: '-e ATmega328P'

ATmega64:
  <<: *pio_run
  variables:
    PLATFORMIO_CI_EXTRA_ARGS: '-e ATmega64'

ATmega644P:
  <<: *pio_run
  variables:
    PLATFORMIO_CI_EXTRA_ARGS: '-e ATmega644P'

ATmega128:
  <<: *pio_run
  variables:
    PLATFORMIO_CI_EXTRA_ARGS: '-e ATmega128'

ATmega1284P:
  <<: *pio_run
  variables:
    PLATFORMIO_CI_EXTRA_ARGS: '-e ATmega1284P'

ATmega2560:
  <<: *pio_run
  variables:
    PLATFORMIO_CI_EXTRA_ARGS: '-e ATmega2560'
