name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        pio-env: [ATmega32,ATmega328P,ATmega64,ATmega644P,ATmega128,ATmega1284P,ATmega2560]

    steps:
    - uses: actions/checkout@v2

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Run PlatformIO for ${{ matrix.build-type }}
      run: pio run -e ${{ matrix.pio-env }}

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-files
        path: |
          .pio/build/*/firmware.hex
          .pio/build/*/firmware.map